apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nylabankservice
  name: nylabankservice
spec:
  ingressClassName: nginx
  rules:
  - host: nylabankapi.prod.maoney.co
    http:
      paths:
      - backend:
          service:
            name: nylabankservice
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nylabankapi.prod.maoney.co
    secretName: ssl-prod-nylabankservice           