"""patch: change default is_active from False to True in User model

Revision ID: 41288f8df2b0
Revises: 7cea8abd2649
Create Date: 2025-06-29 13:31:02.199717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41288f8df2b0"
down_revision: Union[str, Sequence[str], None] = "7cea8abd2649"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
