"""patch: change default is_active from True to False in User model

Revision ID: 7cea8abd2649
Revises: 8fb03193f289
Create Date: 2025-06-29 11:26:04.163025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cea8abd2649'
down_revision: Union[str, Sequence[str], None] = '8fb03193f289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
