---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-test-config
data:
  ENVIRONMENT: production
---
kind: Pod            
apiVersion: v1
metadata:
  name: integration-test
  labels:
    app: integration-test
spec:
  containers:
  - name: integration-test
    image: $IMAGE_NAME:$IMAGE_TAG
    envFrom:
    - configMapRef:
        name: integration-test-config
    readinessProbe:
      httpGet:
        path: /readyz
        port: 3010
      initialDelaySeconds: 15
      periodSeconds: 30
    livenessProbe:
      httpGet:
        path: /livez 
        port: 3010
      initialDelaySeconds: 15
      periodSeconds: 30 
---
kind: Service
apiVersion: v1
metadata:
  name: integration-test-service
spec:
  selector:
    app: integration-test
  ports:
  - port: 3010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: integration-test-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: integration-test-service
            port:
              number: 3010
---

